services:
  # --- MongoDB ---
  mongo:
    image: mongo:7
    container_name: ecommerce-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - ecommerce-network
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # --- User Service ---
  user-service:
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile
    container_name: ecommerce-user-service
    environment:
      - USER_SERVICE_HOST=0.0.0.0
      - USER_SERVICE_PORT=4001
      - MONGO_URI_USER=mongodb://mongo:27017/user-db
      - JWT_SECRET=${JWT_SECRET:-supersecret}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-3600s}
    ports:
      - '4001:4001'
    networks:
      - ecommerce-network
    depends_on:
      - mongo
    restart: unless-stopped

  # --- Product Service ---
  product-service:
    build:
      context: .
      dockerfile: apps/product-service/Dockerfile
    container_name: ecommerce-product-service
    environment:
      - PRODUCT_SERVICE_HOST=0.0.0.0
      - PRODUCT_SERVICE_PORT=4002
      - MONGO_URI_PRODUCT=mongodb://mongo:27017/product-db
    ports:
      - '4002:4002'
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - ecommerce-network
    restart: unless-stopped

  # --- Order Service ---
  order-service:
    build:
      context: .
      dockerfile: apps/order-service/Dockerfile
    container_name: ecommerce-order-service
    environment:
      - CART_SERVICE_HOST=0.0.0.0
      - CART_SERVICE_PORT=4005
      - MONGO_URI_CART=mongodb://mongo:27017/cart-db
      - MONGO_URI_ORDER=mongodb://mongo:27017/order-db
      - PRODUCT_SERVICE_HOST=product-service
      - PRODUCT_SERVICE_PORT=4002
      - PAYMENT_SERVICE_HOST=payment-service
      - PAYMENT_SERVICE_PORT=4004
    ports:
      - '4005:4005'
    networks:
      - ecommerce-network
    depends_on:
      - mongo
    restart: unless-stopped

  # --- API Gateway ---
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    container_name: ecommerce-api-gateway
    environment:
      - PORT_API_GATEWAY=3000
      - USER_SERVICE_HOST=user-service
      - USER_SERVICE_PORT=4001
      - PRODUCT_SERVICE_HOST=product-service
      - PRODUCT_SERVICE_PORT=4002
      - ORDER_SERVICE_HOST=order-service
      - ORDER_SERVICE_PORT=4005
      - PAYMENT_SERVICE_HOST=payment-service
      - PAYMENT_SERVICE_PORT=4004
      - CART_SERVICE_HOST=order-service
      - CART_SERVICE_PORT=4005
      - JWT_SECRET=${JWT_SECRET:-supersecret}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-3600s}
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - user-service
      - product-service
      - order-service
    networks:
      - ecommerce-network
    restart: unless-stopped

volumes:
  mongo-data:
    driver: local

networks:
  ecommerce-network:
    driver: bridge
