name: ecommerce-services

services:
  mongo:
    image: mongo:7
    container_name: ecommerce-mongo
    restart: unless-stopped
    ports:
      - ${MONGO_PORT:-27017}:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - ecommerce-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    image: ${IMAGE_REGISTRY}/user-service:${IMAGE_TAG}
    container_name: ecommerce-user-service
    pull_policy: always
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${USER_SERVICE_PORT:-4001}:4001
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - ecommerce-network

  product-service:
    image: ${IMAGE_REGISTRY}/product-service:${IMAGE_TAG}
    container_name: ecommerce-product-service
    pull_policy: always
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PRODUCT_SERVICE_PORT:-4002}:4002
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - ecommerce-network

  order-service:
    image: ${IMAGE_REGISTRY}/order-service:${IMAGE_TAG}
    container_name: ecommerce-order-service
    pull_policy: always
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${ORDER_SERVICE_PORT:-4005}:4005
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - ecommerce-network

  payment-service:
    image: ${IMAGE_REGISTRY}/payment-service:${IMAGE_TAG}
    container_name: ecommerce-payment-service
    pull_policy: always
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PAYMENT_SERVICE_PORT:-4004}:4004
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - ecommerce-network

  api-gateway:
    image: ${IMAGE_REGISTRY}/api-gateway:${IMAGE_TAG}
    container_name: ecommerce-api-gateway
    pull_policy: always
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PORT_API_GATEWAY:-3000}:3000
    depends_on:
      mongo:
        condition: service_healthy
      user-service:
        condition: service_started
      product-service:
        condition: service_started
      order-service:
        condition: service_started
      payment-service:
        condition: service_started
    networks:
      - ecommerce-network

volumes:
  mongo-data:
    driver: local

networks:
  ecommerce-network:
    driver: bridge
